/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author HP
 */
public class PrintRec extends javax.swing.JFrame {

    /**
     * Creates new form PrintRec
     */
    public PrintRec() {
        initComponents();
        getRecords();
        
    }
    
    public void getRecords()
    {
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/fees_mgmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con = DriverManager.getConnection(url, "root", "JoeBiden@1752");

        PreparedStatement st = con.prepareStatement("SELECT * FROM fees_details ORDER BY reciept_no DESC LIMIT 1");
        ResultSet rs = st.executeQuery();
        rs.next();
        txt_receiptn_no.setText(rs.getString("reciept_no"));
        txt_paymentMode.setText(rs.getString("payment_mode"));
        
        String paymentMode = rs.getString("payment_mode");
        if(paymentMode.equalsIgnoreCase("cash"))
        {
            lbl_chequeDd.setText("cheque No");
            txt_cheque_dd.setText("-");
            txt_bankName.setText("-");   
        }
        
         if(paymentMode.equalsIgnoreCase("cheque"))
        {
            lbl_chequeDd.setText("cheque No");
            txt_cheque_dd.setText(rs.getString("cheque_no"));
            txt_bankName.setText(rs.getString("bank_name"));   
        }
         
         if(paymentMode.equalsIgnoreCase("dd"))
        {
            lbl_chequeDd.setText("DD No");
            txt_cheque_dd.setText(rs.getString("dd_no"));
            txt_bankName.setText(rs.getString("bank_name"));   
        }
         
         txt_recievedfrom.setText(rs.getString("student_name"));
         txt_date.setText(rs.getString("date"));
         txt_gstn.setText(rs.getString("gstin"));
         txt_year1.setText(rs.getString("year1"));
         txt_year2.setText(rs.getString("year2"));
         txt_initialamount.setText(rs.getString("amount"));
         txt_total.setText(rs.getString("total_amount"));
         txt_TotalInWords1.setText(rs.getString("total_in_words"));
         txt_remark.setText(rs.getString("remark"));
         txt_coursename1.setText(rs.getString("course_name"));
         

    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_Home = new javax.swing.JButton();
        btn_EditRecord = new javax.swing.JButton();
        btn_RearchRecord = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        ptn_logout = new javax.swing.JButton();
        btn_AddCourse = new javax.swing.JButton();
        btn_back1 = new javax.swing.JButton();
        panel_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_cheque_dd = new javax.swing.JLabel();
        txt_receiptn_no = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_chequeDd = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_recievedfrom = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_gstn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_coursename1 = new javax.swing.JLabel();
        txt_initialamount = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_sgst4 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_TotalInWords1 = new javax.swing.JLabel();
        txt_sgst6 = new javax.swing.JLabel();
        txt_sgst7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(255, 153, 153));
        btn_Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setText("HOME");
        btn_Home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
        });
        jPanel3.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 47, 190, -1));

        btn_EditRecord.setBackground(new java.awt.Color(255, 153, 153));
        btn_EditRecord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_EditRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_EditRecord.setText("EDIT RECORD");
        btn_EditRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_EditRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditRecordMouseClicked(evt);
            }
        });
        jPanel3.add(btn_EditRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 165, 182, -1));

        btn_RearchRecord.setBackground(new java.awt.Color(255, 153, 153));
        btn_RearchRecord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_RearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_RearchRecord.setText("SEARCH RECORD");
        btn_RearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_RearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RearchRecordMouseClicked(evt);
            }
        });
        btn_RearchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RearchRecordActionPerformed(evt);
            }
        });
        jPanel3.add(btn_RearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 105, 182, -1));

        btn_print.setBackground(new java.awt.Color(255, 153, 153));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel3.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 182, 30));

        ptn_logout.setBackground(new java.awt.Color(255, 153, 153));
        ptn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ptn_logout.setForeground(new java.awt.Color(255, 255, 255));
        ptn_logout.setText("LOGOUT");
        ptn_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        jPanel3.add(ptn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 182, -1));

        btn_AddCourse.setBackground(new java.awt.Color(255, 153, 153));
        btn_AddCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_AddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddCourse.setText("ADD COURSE");
        btn_AddCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddCourseActionPerformed(evt);
            }
        });
        jPanel3.add(btn_AddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 182, -1));

        btn_back1.setBackground(new java.awt.Color(255, 153, 153));
        btn_back1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_back1.setForeground(new java.awt.Color(255, 255, 255));
        btn_back1.setText("BACK");
        btn_back1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), java.awt.Color.white, null, null));
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 182, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 660));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Desktop\\image\\CLG LOGO_page-002.jpg")); // NOI18N
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 100));

        jSeparator1.setForeground(new java.awt.Color(204, 153, 255));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 200, 10));

        txt_cheque_dd.setText("cheque_dd :");
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 20));

        txt_receiptn_no.setText("Receipt no :");
        panel_print.add(txt_receiptn_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        txt_paymentMode.setText("Payment mode :");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel5.setText("Received from  for the given month :");
        panel_print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        lbl_chequeDd.setText("cheque_dd :");
        panel_print.add(lbl_chequeDd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_bankName.setText("Bank Name :");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 20));

        txt_year2.setText("2021");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        txt_recievedfrom.setText("Recieved From :");
        panel_print.add(txt_recievedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel10.setText("-");
        panel_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 20, -1));

        txt_year1.setText("2021");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel12.setText("Payment mode :");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setText("Receipt no :");
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        lbl_bankName.setText("Bank Name :");
        panel_print.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        txt_gstn.setText("GSTN :");
        panel_print.add(txt_gstn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel15.setText("Amount(rs)");
        panel_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        txt_date.setText("Date :");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel17.setText("GSTN :");
        panel_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel18.setText("Date :");
        panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(204, 153, 255));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 570, 20));

        jSeparator3.setForeground(new java.awt.Color(204, 153, 255));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 570, 10));

        jLabel16.setText("Recieved Name :");
        panel_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        jLabel20.setText("Course enrollment");
        panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel21.setText("Total Fees :");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 70, -1));

        jLabel22.setText("1");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 30, -1));

        txt_coursename1.setText("1");
        panel_print.add(txt_coursename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 80, 20));

        txt_initialamount.setText("amount :");
        panel_print.add(txt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, -1));

        txt_total.setText("total");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 80, 20));

        jSeparator4.setForeground(new java.awt.Color(204, 153, 255));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 570, 10));

        txt_sgst4.setText("Receiver Signiture");
        panel_print.add(txt_sgst4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 120, -1));

        txt_remark.setText("remark :");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 80, -1));

        jSeparator5.setForeground(new java.awt.Color(204, 153, 255));
        panel_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, 10));

        txt_TotalInWords1.setText("total in words :");
        panel_print.add(txt_TotalInWords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 250, 20));

        txt_sgst6.setText("Fee In Words :");
        panel_print.add(txt_sgst6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 80, -1));

        txt_sgst7.setText("remark :");
        panel_print.add(txt_sgst7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 80, -1));

        jLabel23.setText("Sr No");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel24.setText("Paid fees :");
        panel_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 60, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 590, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RearchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RearchRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RearchRecordActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddCourseActionPerformed

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked

        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_RearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RearchRecordMouseClicked
     SearchRecords searchrecord = new SearchRecords();
     searchrecord.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btn_RearchRecordMouseClicked

    private void btn_EditRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditRecordMouseClicked
      EditCourse editrecord = new EditCourse();
      editrecord.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btn_EditRecordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddCourse;
    private javax.swing.JButton btn_EditRecord;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_RearchRecord;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_chequeDd;
    private javax.swing.JPanel panel_print;
    private javax.swing.JButton ptn_logout;
    private javax.swing.JLabel txt_TotalInWords1;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_coursename1;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstn;
    private javax.swing.JLabel txt_initialamount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptn_no;
    private javax.swing.JLabel txt_recievedfrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst4;
    private javax.swing.JLabel txt_sgst6;
    private javax.swing.JLabel txt_sgst7;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
