/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Signup_page extends javax.swing.JFrame {

    /**
     * Creates new form Signup_page
     */
   private Connection conn;
    
    public Signup_page() {
        initComponents();
        connectToDatabase();
    }
    
    private void connectToDatabase() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_mgmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL";
            conn = DriverManager.getConnection(url, "root", "JoeBiden@1752");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    private int getId() {
        int id = 0;
        try {
            String sql = "SELECT MAX(id) FROM signup";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                id = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cnumber = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_cpfield = new javax.swing.JPasswordField();
        txt_pfield = new javax.swing.JPasswordField();
        txt_uname = new javax.swing.JTextField();
        txt_dob = new com.toedter.calendar.JDateChooser();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_cnumbererror = new javax.swing.JLabel();
        lbl_passworderror = new javax.swing.JLabel();
        lbl_cpassworderror1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Contact Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("D.O.B");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, -1));

        txt_cnumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnumberActionPerformed(evt);
            }
        });
        txt_cnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 160, -1));

        txt_fname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 160, -1));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 160, -1));

        txt_cpfield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfieldActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 160, -1));

        txt_pfield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_pfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txt_pfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, -1));

        txt_uname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, -1));
        getContentPane().add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, 30));

        btn_login.setBackground(new java.awt.Color(255, 204, 204));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(102, 102, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 90, -1));

        btn_signup.setBackground(new java.awt.Color(255, 204, 204));
        btn_signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(102, 102, 255));
        btn_signup.setText("SigUp");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 90, -1));

        btn_clear.setBackground(new java.awt.Color(255, 204, 204));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(102, 102, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 90, -1));

        lbl_cnumbererror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cnumbererror.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbl_cnumbererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 250, 30));

        lbl_passworderror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_passworderror.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbl_passworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 250, 30));

        lbl_cpassworderror1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cpassworderror1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbl_cpassworderror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnumberActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unameActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
  // TODO add your handling code here: 
     if (validateFields()) {
            insertData();
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void txt_cpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfieldActionPerformed

    private void txt_pfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pfieldKeyPressed
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_txt_pfieldKeyPressed

    private void txt_pfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pfieldKeyReleased
        // TODO add your handling code here:
         passwordCheck();
    }//GEN-LAST:event_txt_pfieldKeyReleased

    private void txt_pfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pfieldKeyTyped
        // TODO add your handling code here:
         passwordCheck();
    }//GEN-LAST:event_txt_pfieldKeyTyped

    private void txt_cnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnumberKeyPressed
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txt_cnumberKeyPressed

    private void txt_cnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnumberKeyReleased
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txt_cnumberKeyReleased

    private void txt_cnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnumberKeyTyped
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txt_cnumberKeyTyped

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        Login l1=new Login();
        l1.show();
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_fname.setText("");
        txt_lname.setText("");
        txt_uname.setText("");
        txt_pfield.setText("");
        txt_cpfield.setText("");
        //txt_dob.getDate();
        txt_cnumber.setText("");
        
    }//GEN-LAST:event_btn_clearActionPerformed
     String fname,lname,uname,password,cpassword,cnumber;
        Date dob;
       
 private void insertData() {
        try {
            String sql = "INSERT INTO signup VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement st = conn.prepareStatement(sql);

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dobStr = dateFormat.format(txt_dob.getDate());

            st.setInt(1, getId() + 1); // Increment ID
            st.setString(2, txt_fname.getText());
            st.setString(3, txt_lname.getText());
            st.setString(4, txt_uname.getText());
            st.setString(5, txt_pfield.getText());
            st.setString(6, dobStr);
            st.setString(7, txt_cnumber.getText());

            int rowsInserted = st.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Record Inserted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Record Not Inserted");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
       private boolean validateFields() {
        String fname = txt_fname.getText();
        String lname = txt_lname.getText();
        String uname = txt_uname.getText();
        String password = txt_pfield.getText();
        String cpassword = txt_cpfield.getText();
        Date dob = txt_dob.getDate();
        String cnumber = txt_cnumber.getText();

        if (fname.isEmpty() || lname.isEmpty() || uname.isEmpty() ||
            password.isEmpty() || cpassword.isEmpty() || dob == null || cnumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return false;
        }

        if (!password.equals(cpassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match");
            return false;
        }

        return true;
    }

    
    void passwordCheck()
    {
     password=txt_pfield.getText();
     if(password.length()>=8)
     {
     lbl_passworderror.setText("");
     }
     else
     {
     lbl_passworderror.setText("Enetr 8 digit password");
     }
    }
    
    void mobileCheck()
    {
     cnumber=txt_cnumber.getText();
    if(cnumber.length()==10)
    {
    lbl_cnumbererror.setText("");
    }
    else
    {
    lbl_cnumbererror.setText("Eneter 10 digit number");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cnumbererror;
    private javax.swing.JLabel lbl_cpassworderror1;
    private javax.swing.JLabel lbl_passworderror;
    private javax.swing.JTextField txt_cnumber;
    private javax.swing.JPasswordField txt_cpfield;
    private com.toedter.calendar.JDateChooser txt_dob;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JPasswordField txt_pfield;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables

    private static class Connectin {

        public Connectin() {
        }

        private PreparedStatement prepareStatement(String sql) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private Statement createStatement() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
